name: Build Kernel - A13

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:
    inputs:
      kernelsu_variant:
        required: true
        type: string
      kernelsu_branch:
        required: true
        type: string
      kernelsu_branch_other:
        required: false
        type: string
        default: ""

jobs:
  build-kernels-a13-5-15:
    strategy:
      fail-fast: true
      matrix:
        include:
          - sub_level: "123"
            os_patch_level: "2023-11"
          - sub_level: "148"
            os_patch_level: "2024-05"
          - sub_level: "167"
            os_patch_level: "2024-11"
          - sub_level: "180"
            os_patch_level: "2025-05"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android13"
      kernel_version: "5.15"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other || '' }}
